# Generated by Django 5.1.2 on 2024-12-06 22:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Meta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Alvo')),
                ('progresso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Progresso Atual')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('em_progresso', 'Em Progresso'), ('alcançada', 'Alcançada'), ('não_alcançada', 'Não Alcançada')], default='em_progresso', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Contribuição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Contribuído')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='goals.meta', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Registro de Meta',
                'verbose_name_plural': 'Registros de Metas',
                'ordering': ['-data'],
            },
        ),
    ]
