# Generated by Django 5.1.2 on 2024-12-14 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id_relatorio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID do Relatório')),
                ('tipo', models.CharField(choices=[('transacoes', 'Transações'), ('usuarios', 'Usuários'), ('contas', 'Contas'), ('customizado', 'Customizado')], max_length=20, verbose_name='Tipo de Relatório')),
                ('parametros', models.JSONField(blank=True, null=True, verbose_name='Parâmetros Personalizados')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_processamento', 'Em Processamento'), ('concluido', 'Concluído'), ('falha', 'Falha')], default='pendente', max_length=20, verbose_name='Status do Relatório')),
                ('caminho_arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/%Y/%m/%d/', verbose_name='Caminho do Arquivo')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='LogRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Log')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.relatorio', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Log de Relatório',
                'verbose_name_plural': 'Logs de Relatórios',
                'ordering': ['-data'],
            },
        ),
    ]
